replicaCount: 2
revisionHistoryLimit: 2
namespace: currency-app
label:
  key: app
  value: currency
image:
  repository: belyaevedu/restapi-currency
  tag: v1.0.5
container:
  port: 8000
  probe:
    liveness:
      path: /docs
      initialDelay: 7
      period: 5
    readiness:
      path: /info/currency?date=2025-12-11
      initialDelay: 10
      period: 30
service:
  port: 8000
ingress:
  enabled: true
  className: cilium
  host: currency.belyaev.work
  serviceType: ClusterIP
certificate:
  email: veniamin@belyaev.work
  server: https://acme-v02.api.letsencrypt.org/directory
  secretRef: letsencrypt-account-key
  issuerName: cert-issuer
  sslRedirectAnnotation:
    name: ingress.cilium.io/force-https
    value: disabled # has to be disabled
