{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: {{ .Values.certificate.email }}
    server: {{ .Values.certificate.server }}
    privateKeySecretRef:
      name: {{ .Values.certificate.secretRef }}
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.ingress.className }}
            podTemplate:
              metadata:
                annotations:
                  {{ .Values.certificate.sslRedirectAnnotation.name }}: {{ .Values.certificate.sslRedirectAnnotation.value }}
{{- end }}