apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{ .Values.label.key }}: {{ .Values.label.value }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      {{ .Values.label.key }}: {{ .Values.label.value }}
  template:
    metadata:
      labels:
        {{ .Values.label.key }}: {{ .Values.label.value }}
        {{ .Values.observability.label.key | quote }}: {{ .Values.observability.label.value | quote }}
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers: # converted from docker-compose.yml via kompose
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: restapi-currency
          ports:
            - containerPort: {{ .Values.container.port }}
              protocol: TCP
            - containerPort: {{ .Values.container.metrics.port }}
              protocol: TCP
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsUser: 1000
          volumeMounts:
            - mountPath: /app/requester/cache
              name: restapi-currency-tmpfs0
            - mountPath: /tmp
              name: restapi-currency-tmpfs1
          livenessProbe:
            httpGet:
              path: {{ .Values.container.probe.liveness.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.probe.liveness.initialDelay }}
            periodSeconds: {{ .Values.container.probe.liveness.period }}
          readinessProbe:
            httpGet:
              path: {{ .Values.container.probe.readiness.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.probe.readiness.initialDelay }}
            periodSeconds: {{ .Values.container.probe.readiness.period }}
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: restapi-currency-tmpfs0
        - emptyDir:
            medium: Memory
          name: restapi-currency-tmpfs1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: {{ .Values.label.key }}
                operator: In
                values:
                - {{ .Values.label.value }}
            topologyKey: "kubernetes.io/hostname"
