apiVersion: v1
kind: Service
metadata:
  name: currency-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{ .Values.label.key }}: {{ .Values.label.value }}
  ports:
    - name: http
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.service.appPort }}
    - name: metrics
      port: {{ .Values.container.metrics.port }}
      targetPort: {{ .Values.service.metricsPort }}
